server:
 port: ${PORT:9999}
spring:
 application.name: aggregatorCluster
security.basic.enabled: false

turbine:

 appConfig: gatewayEdgeServer,recommendations
 aggregator:
  clusterConfig: GATEWAYEDGESERVER,RECOMMENDATIONS
  

eureka.client.serviceUrl.defaultZone: http://localhost:9000/eureka/