server:
  port: ${PORT:9010}

eureka:
  enableSelfPreservation: false
  instance:
    hostname: peer1
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  server:
    enableSelfPreservation: false
