spring:
 profiles: docker

server:
  port: 9000

eureka:
  instance:
    hostname: eurekasrv
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#spring.cloud.config.discovery.enabled: true