spring:
 profiles: docker
 
logging.file: /tmp/membership.log

server:
  port: ${PORT:9003}

security:
  basic:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekasrv:9000/eureka/
  instance:
   preferIpAddress : true
   metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      
#spring.cloud.config.discovery.enabled: true