spring:
  application:
    name: recommendations
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
security:
  basic:
    enabled: false
eureka:
  leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress : true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}

#logging.pattern.console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'
