spring:
 profiles: docker
 
logging.file: /tmp/racommendation.log
server:
  port: ${PORT:9002}

security:
  basic:
    enabled: false
eureka:
  leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://eurekasrv:9000/eureka/
  instance:
    preferIpAddress : true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}